/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package corto;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JComponent;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class registro extends javax.swing.JFrame {

    /**
     * Creates new form registro
     */
    final DefaultListModel model = new DefaultListModel();
    ArrayList<estudiante> mocos = new ArrayList<estudiante>();

    public registro() {
        initComponents();
        
        
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txtnombre = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        rbtnagregar = new javax.swing.JRadioButton();
        rbtnbuscar = new javax.swing.JRadioButton();
        rbtneditar = new javax.swing.JRadioButton();
        rbtneliminar = new javax.swing.JRadioButton();
        btnaccion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstestudiantes = new javax.swing.JList<>();
        lblresultado = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        txtgrado = new javax.swing.JTextField();
        btnsalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });

        txtapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapellidoActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label1.setText("Nombre:");

        label2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label2.setText("Apellido:");

        buttonGroup1.add(rbtnagregar);
        rbtnagregar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtnagregar.setText("Agregar");
        rbtnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnagregarActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnbuscar);
        rbtnbuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtnbuscar.setText("Buscar");

        buttonGroup1.add(rbtneditar);
        rbtneditar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtneditar.setText("Editar");

        buttonGroup1.add(rbtneliminar);
        rbtneliminar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtneliminar.setText("Eliminar");

        btnaccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnaccion.setText("Aceptar");
        btnaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaccionActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lstestudiantes);

        label3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label3.setText("Grado:");

        txtgrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgradoActionPerformed(evt);
            }
        });

        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnaccion)
                .addGap(181, 181, 181))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(15, 15, 15))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rbtnagregar)
                                .addComponent(rbtneditar))
                            .addGap(88, 88, 88)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rbtnbuscar)
                                .addComponent(rbtneliminar))
                            .addGap(19, 19, 19))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(35, 35, 35)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtapellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                                .addComponent(txtnombre, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtgrado))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(lblresultado, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtgrado, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnagregar)
                    .addComponent(rbtnbuscar))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtneditar)
                    .addComponent(rbtneliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnaccion)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(lblresultado, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnsalir)
                        .addGap(25, 25, 25))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapellidoActionPerformed
        // TODO add your handling code here:
        //Esta es la entrada del apellido
        ((JComponent) evt.getSource()).transferFocus();
    }//GEN-LAST:event_txtapellidoActionPerformed

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
        //Esta es la entrada del nombre
        ((JComponent) evt.getSource()).transferFocus();
    }//GEN-LAST:event_txtnombreActionPerformed

    private void txtgradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgradoActionPerformed
        // TODO add your handling code here:
        //Entrada del grado (innecesario)
        ((JComponent) evt.getSource()).transferFocus();
    }//GEN-LAST:event_txtgradoActionPerformed

    private void btnaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaccionActionPerformed
                
       
        
        // TODO add your handling code here:
        if (rbtnagregar.isSelected()) {
            //Checkbox para agregar registro
            control control = new control();
            //mocos es el arraylist para guardar los registros
            mocos = control.Guardar(txtnombre.getText(), txtapellido.getText(), txtgrado.getText());
            for (estudiante c : mocos) {
                System.out.println(c);
                //modelo de lista y la concatenacion de todos los elementos
                model.addElement(c.nombre +" "+ c.apellido +" "+c.grado +" "+ c.carnet);
            }
            lstestudiantes.setModel(model);
        txtnombre.setText("");
        txtapellido.setText("");
        txtgrado.setText("");
        }
        if (rbtneliminar.isSelected()) {
            //Checkbox para la opcion eliminar
            //Recursividad en la ventana de ingresar carnet
            carnet carnet = new carnet();
            carnet.setVisible(true);
            this.dispose();
            control eliminar=new control();
            eliminar.editar();         


        }
        if (rbtneditar.isSelected()) {
            //Checkbox para editar registro
            //Recursividad de ventana
            carnet carnet = new carnet();
            carnet.setVisible(true);
            this.dispose();
            control editar=new control();
            editar.editar(editar);

        }
        if (rbtnbuscar.isSelected()) {
           
           control buscar=new control();
           buscar.Buscar();
            //Checkbox para buscar un registro
            //Recursividad de ventana
            carnet carnet = new carnet();
            carnet.setVisible(true);
            this.dispose();
            control control = new control();
            //mocos es el arraylist para guardar los registros
            mocos = control.Buscar(txtnombre.getText(), txtapellido.getText(), txtgrado.getText());
            registro reg = new registro();
           lblresultado.setText(txtnombre.getText()+""+txtapellido.getText()+""+txtgrado.getText());
            for (estudiante c : mocos) {
             
                
            }
        } 
       
    }//GEN-LAST:event_btnaccionActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        //Boton para salir
        System.exit(0);
    }//GEN-LAST:event_btnsalirActionPerformed

    private void rbtnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnagregarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_rbtnagregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaccion;
    private javax.swing.JButton btnsalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel lblresultado;
    private javax.swing.JList<String> lstestudiantes;
    private javax.swing.JRadioButton rbtnagregar;
    private javax.swing.JRadioButton rbtnbuscar;
    private javax.swing.JRadioButton rbtneditar;
    private javax.swing.JRadioButton rbtneliminar;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtgrado;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
